### ISSUE TITLE
Consider min liquidity burn 

### ISSUE THREAD

**Issue by 0xean** [ElasticSwap/elasticswap#22]
See https://uniswap.org/docs/v2/protocol-overview/smart-contracts/#minimum-liquidity for more info on why this is done in uniswap.

It could possibly alleviate some of the issues around imprecision in our decay.

**Comment by pelsasser** [comment]
https://github.com/Uniswap/uniswap-v2-core/blob/4dd59067c76dea4a0e8e4bfdda41877a6b16dedc/contracts/UniswapV2Pair.sol#L119

**Comment by pelsasser** [comment]
@pelsasser to reach out to uni to understand the min burn.
