### ISSUE TITLE
Add support for Fee on Transfer tokens

### ISSUE THREAD

**Issue by 0xean** [ElasticSwap/elasticswap#45]
#### Background
Currently we aren't fully supporting fee on transfer tokens. We assume in the codebase that the amount input == amount output for all erc20 transactions which is not the case for FOTT (Fee on Transfer Tokens). 

Other AMMs have dealt with this by calculating the delta between their expected balances and their new balances after an amount is sent, this wont completely work with Elastic supply tokens, but we can check the balance before and after the transfer in order to be sure of the qty that has been received by the exchange.

This has implications to gas costs and some of the transaction ordering that is currently taking place and will require a little more work than anticipated in order to fully support these tokens in a generic fashion.

#### AC
- Implement FOTT mock (see #40 for a link to an example)
 - Modify Swap, and Liquidity functions to allow for fee on transfer tokens
 - Add full test coverage for new functionality with FOTT mock.

**Comment by pelsasser** [comment]
After attempting a few different potential solutions, I think this is best left to a feature we tackle in v2 fo ElasticSwap
